---
version: "3.8"
services:

  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    volumes:
      - ~/heimdall/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    devices:
      - "/dev/dri/renderD128:/dev/dri/renderD128"
    volumes:
      - ~/jellyfin/config:/config
      - ~/jellyfin/cache:/cache
      - ~/media/tvshows:/data/tvshows
      - ~/media/movies:/data/movies
      - ~/media/music:/data/music
      - ~/media/anime:/data/anime
    ports:
      - 8096:8096
    restart: unless-stopped

  camip:
    image: gen2brain/cam2ip
    container_name: cam2ip
    devices:
      - "/dev/video0:/dev/video0"
    ports:
      - 56000:56000

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - WEBUI_PORT=8080
    volumes:
      - ~/qbittorrent/config:/config
      - ~/Downloads:/downloads
      - ~/media:/media
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - ~/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - ~/sonarr/config:/config
      - ~/media/tvshows:/tv
      - ~/media/anime:/anime
      - ~/Downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - ~/radarr/config:/config
      - ~/media/movies:/movies 
      - ~/Downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  jellyseerr:
     image: fallenbagel/jellyseerr:latest
     container_name: jellyseerr
     environment:
          - LOG_LEVEL=debug
          - TZ=Asia/Kolkata
     ports:
          - 5055:5055
     volumes:
          - ~/jellyseerr/config:/app/config
     restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - ~/lidarr/config:/config
      - ~/media/music:/music
      - ~/Downloads:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped
